- name: reload apache service on debian
  ansible.builtin.service:
    name: apache2
    state: restarted
    enabled: true
  tags: reload
  when: "ansible_facts['os_family'] == 'Debian'"

- name: reload apache service on rocky
  ansible.builtin.service:
    name: httpd
    state: restarted
    enabled: true
  tags: reload
  when: "ansible_facts['os_family'] == 'RedHat'"
