- name: change config
  ansible.builtin.template:
    src: templates/ports.j2
    dest: /etc/apache2/ports.conf
    owner: www-data
    group: www-data
    mode: 0664
  when: "ansible_facts['os_family'] == 'Debian'"
  notify:
