- name: debug version
  arista.eos.eos_command:
    commands: "show version"
  register: version

- debug:
    msg: "Device is running {{ version }}"

- name: Gathering interfaces facts
  arista.eos.eos_facts:
    gather_subset:
    - interfaces

- name: Configure interfaces
  arista.eos.eos_config:
    src: "{{ item }}"
    save_when: always
  loop:
    - Ethernet1.cfg
    - Ethernet2.cfg